import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { OAuthSessionSync } from "@/components/providers/OAuthSessionSync";

import { NotificationProvider } from "@/components/common/NotificationProvider";
import { DataInitializer } from "@/components/providers/DataInitializer";
import { CommandPalette } from "@/components/command/CommandPalette";
import { PageTracker } from "@/components/providers/PageTracker";
import { ToasterProvider } from "@/components/providers/ToasterProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <ThemeProvider defaultTheme="system" storageKey="githubmon-theme">
            <OAuthSessionSync />
            <DataInitializer />
            <PageTracker />
            <CommandPalette />
            <ToasterProvider />
            {children}
            <NotificationProvider />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
